site_name: PGSbuilder
theme: readthedocs

nav:
  - Home: index.md
  - Submitting a Job: submitting-a-job.md
  - Pipeline Overview: pipeline-overview.md
  - Interpreting the Result: interpreting-the-result.md
  - Security: security.md

repo_name: ailabstw/PGSbuilder
repo_url: https://github.com/ailabstw/PGSbuilder
edit_uri: edit/main/docs

extra:
  social:
    - type: github-alt
      link: https://github.com/ailabstw/PGSbuilder

markdown_extensions:
  - attr_list

plugins:
  - with-pdf